@startuml

entity Move {
    id: int
    name: varchar
    start_fen: varchar
    end_fen: varchar
}

entity Game {
    id: int
    white_player: varchar
    black_player: varchar
    result: varchar
    site: int
    source: varchar
}

entity "Game Move" as game_move {
    id: int
    game_id: game(id)
    move_id: move(id)
}

entity "Position Note" {
    id: int
    note: varchar
    position: varchar
}

Game "0..*" -- "1..*" Move
(Game, Move) . game_move

@enduml